name: Classic-HC
version: 0.1
author: Enrique
main: devep.ClassicHC
api-version: 1.16
depend:
  - WorldBorderAPI
softdepend: [TitleManager, PlaceholderAPI]
commands:
  forceStartGame:
    description: Forzar el inicio de la partida
    usage: /forceStartGame
    permission: classichc.forcestartgame